---

nccl_tests_sha_map:
  # cuda: nccl_tests: architecture
  "12.9.0":
    "2.16.4":
      "x86_64": "sha256:2fbff680f180fd3ff674dd14a33e6c7506f499788bf3a5d9ec899876756da944"
      "aarch64": "sha256:248a345c38faeca93ebe7699fdf932d576c325d6d8597a1102e2b16a62c541c9"
    "2.17.6":
      "x86_64": "sha256:c780197008e1d104a7bd622d262497856dc4e442d80bc1a0157ece2f1559d65a"
      "aarch64": "sha256:a6b6cc982db55fe5119b1a4ea4a739d538b2b6ad8e3f212e7f87ad3eae9311c3"
    "2.17.7":
      "x86_64": "sha256:9a05d96af3524cb4996a6b80a954f7a5b42e86533705405cdb2cbe7db79e22de"
      "aarch64": "sha256:8687700ef3d0f8410ea6d2955f598ddb470a16d66c0a23b18f66834b6a69ca10"
    "2.17.8":
      "x86_64": "sha256:03f26353650efa2bf4b4e994411df239c9332fb98b7971c9075f628cd3ec0a18"
      "aarch64": "sha256:039c9c91d40bd08cbe256dfd77d29698ac38e57a7f90d407b9e495b4bf01ab6d"
    "2.17.9":
      "x86_64": "sha256:df0a43032bcd3920de71316f3baa8c7a4f87b4dfd44cb782b2487bdaa6a189ea"
      "aarch64": "sha256:b6ee46395b8017c0a9ff5829cca5a7bd9e1a9473a36a141dfd3e3847d94b55e9"
  "13.0.2":
    "2.17.6":
      "x86_64": "sha256:e24db0de81e0cf4792a12c329f5d81dcc328c53fab7ada942e4588f303c6e332"
      "aarch64": "sha256:b686693104ad10291070f000fac39cb31575a636211135a9d7719172c2cf94b4"
    "2.17.7":
      "x86_64": "sha256:652444fc1a8ecdbe0a8d3b2fafa2853516b34b444107aa00f10b1413f3f4480d"
      "aarch64": "sha256:a10135034bf811ba5733ed4e40c48736a7aafd161947a977e8301e5e28783507"
    "2.17.8":
      "x86_64": "sha256:05ffe66717fa02bd665e41971d2fe53ac7b81337f4f03da65a24cd0a79cda4c2"
      "aarch64": "sha256:3ae173d88cd9db34455a72322c99e39490c31164948174c5e13ceb8f1875a2a2"
    "2.17.9":
      "x86_64": "sha256:58732b440bfa828f5085e7c5b573fe8043c7415398b400c21c68c5f51b1215e5"
      "aarch64": "sha256:81830cbd5510848ec3ad686ea10382a46b5ba87c71c5946645803f9fe59ec6db"
