name: Build cuda images

on:
  workflow_dispatch:
    inputs:
      cuda_version:
        description: "Version of CUDA to build"
        required: true
        default: "12.9.0"
        type: string
      ubuntu_version:
        description: "Version of the base image of ubuntu"
        required: true
        default: "ubuntu24.04"
        type: string
      nccl_version:
        description: "NCCL lib version"
        required: true
        default: "nccl2.26.5-1"
        type: string

jobs:
  cuda:
    uses: ./.github/workflows/old/base_cuda.yml
    with:
      dockerfile_path: "./cuda/cuda.${{ github.event.inputs.cuda_version }}.dockerfile"
      cuda_version: "${{ github.event.inputs.cuda_version }}"
      ubuntu_version: "${{ github.event.inputs.ubuntu_version }}"
      nccl_version: "${{ github.event.inputs.nccl_version }}"
