---

- name: Install slurm client
  hosts:
    - localhost
    - all
  become: true
  gather_facts: true
  gather_subset:
    - min
  roles:
    - slurm-client
    - slurm-divert
  tags:
    - slurm-client
