name: Build training_diag images

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: X64

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: training_diag-cuda12
            cuda_major: "12"
            cuda_version: "12.9.0"
            ubuntu_version: "ubuntu24.04"
            dcgmi_version: "1:4.4.2-1"
            nccl_tests_version: "2.16.4"
            openmpi_version: "4.1.7a1-1.2404066"
            openmpi_version_short: "4.1.7a1"
            ofed_version: "24.04-0.7.0.0"
            ucx_version: "1.17.0-1.2404066"
          - name: training_diag-cuda13
            cuda_major: "13"
            cuda_version: "13.0.2"
            ubuntu_version: "ubuntu24.04"
            dcgmi_version: "1:4.4.2-1"
            nccl_tests_version: "2.17.6"
            openmpi_version: "4.1.7a1-1.2404066"
            openmpi_version_short: "4.1.7a1"
            ofed_version: "24.04-0.7.0.0"
            ucx_version: "1.17.0-1.2404066"

    name: Build and push image for ${{ matrix.name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Add docker-credential-nebius to PATH
        run: echo "/home/ml_containers/.nebius/bin" >> $GITHUB_PATH

      - name: Set daytime
        run: echo "DAYTIME=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Get image version name
        run: echo "cr.eu-north1.nebius.cloud/ml-containers/training_diag:${{ matrix.cuda_version }}-${{ matrix.ubuntu_version }}-${{ env.DAYTIME }}"

      - name: Build and push images
        # https://console.eu.nebius.com/project-e00managed-schedulers/registry/registry-e00hrt9na9xsn2px9f
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg CUDA_MAJOR=${{ matrix.cuda_major }} \
            --build-arg CUDA_VERSION=${{ matrix.cuda_version }} \
            --build-arg DCGMI_VERSION=${{ matrix.dcgmi_version }} \
            --build-arg NCCL_TESTS_VERSION=${{ matrix.nccl_tests_version }} \
            --build-arg OPENMPI_VERSION=${{ matrix.openmpi_version }} \
            --build-arg OPENMPI_VERSION_SHORT=${{ matrix.openmpi_version_short }} \
            --build-arg OFED_VERSION=${{ matrix.ofed_version }} \
            --build-arg UCX_VERSION=${{ matrix.ucx_version }} \
            -t cr.eu-north1.nebius.cloud/ml-containers/training_diag:${{ matrix.cuda_version }}-${{ matrix.ubuntu_version }}-${{ env.DAYTIME }} \
            --target training_diag \
            --push \
            --progress=plain \
            .
